### ISSUE TITLE
Issue with multiple sources.

### ISSUE THREAD

**Issue by userwiths** [nordcomputer/magento2-stockfilter#13] opened 2023-07-13 09:40 UTC
Hey,
First off, thx for the module and hard work.
Second: While using the module on `2.4.3` magento, our client said that the data was not correct.
I checked, and after a few hours of debugging left and right found this [StackOverflow Discussion](https://magento.stackexchange.com/a/332557).
Long story short, `cataloginventory_stock_item` is used at the moment in the module, while for multiple-sources `inventory_source_item` has the correct data. 
I came up with the following query
``` sql
UPDATE catalog_product_entity_int AS t 
JOIN eav_attribute ea ON ea.attribute_id = t.attribute_id 
JOIN 
    (SELECT t.value_id,t.entity_id,
                t.value,MAX(a.quantity) AS max_qty, MAX(a.status) AS max_status,MIN(a.status) AS min_status 
    FROM catalog_product_entity_int t
    JOIN catalog_product_entity cpe ON cpe.entity_id = t.entity_id
    JOIN inventory_source_item a ON a.sku = cpe.sku
    JOIN eav_attribute ap ON ap.attribute_id = t.attribute_id
        WHERE attribute_code = 'filter_stock' 
        GROUP BY t.entity_id) 
    AS TEMP_TABLE ON TEMP_TABLE.value_id = t.value_id 
    SET t.value = IF(TEMP_TABLE.max_qty > 0 AND TEMP_TABLE.max_status = 1, 1, 0);
```

which worked for our case.
Might open a PR in the following days, but wanted to share this information.

**Comment by nordcomputer** [comment] 2023-07-13 12:40
Hey @userwiths,
 interesting - tbh. I am not a fan of the new inventory system. Feel free to create a PR :)

**Comment by nordcomputer** [comment] 2023-07-25 07:51
Hey @userwiths,

I just merged your PR into the new [develop](https://github.com/nordcomputer/magento2-stockfilter/tree/develop) branch and made some smaller changes to meet the coding standard. Could you check, if the [develop](https://github.com/nordcomputer/magento2-stockfilter/tree/develop) branch is working as intended on your side?

**Comment by userwiths** [comment] 2023-07-26 11:29
Yeah, saw some of the code-style issues but was caught up in other stuff.
Anyway, tested the code from the [develop](https://github.com/nordcomputer/magento2-stockfilter/tree/develop) branch on both instances mentioned in the PR (one with MSI and one without it) and it worked as expected in both.
All seems OK on my side :+1:  .

**Closed as completed** 2023-07-26 12:05 UTC
Labels: bug
